ktor:
  application:
        modules:
            - com.ramihalabi.config.ApplicationKt.module
  deployment:
       port: 8080
  development: true
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
